### ISSUE TITLE
Add Jam options to package.json

### ISSUE THREAD

**Issue by Phoscur** [webpack/example-app#3]

**Comment by sokra** [comment]
Good Point. Bootstrap was updated so it didn't work anymore. Fixed this.

They way this app uses bootstrap is a bit odd, as it's a bit older. They way it's done in the bootstrap-wpt-module is better. See [wpt tutorial](https://github.com/webpack/template/wiki/Tutorial)

**Comment by Phoscur** [comment]
Dont forget:

```
"jam": {
    "packageDir": "web_modules",
```

**Comment by Phoscur** [comment]
Or does webpack import from jam by itself?

**Comment by sokra** [comment]
Yes, but this will be removed in future webpack 0.8

`webpackOptions.resolve.modulesDirectorys` will currently default to: `["web_modules", "jam", "node_modules"]`
