### ISSUE TITLE
require jquery

### ISSUE THREAD

**Issue by Phoscur** [webpack/example-app#4]
client.js:l1

```
require("jquery");
```

Shouldn't it be

```
var $ = require("jquery");
```

?
This is behaving diffrently in node and on the browser. It should be the same.

**Comment by sokra** [comment]
The version of jquery published in the jam registry only exports jquery as AMD module if `define.amd.jQuery == true`.

See this code fragment:

``` javascript
// Expose jQuery to the global object
window.jQuery = window.$ = jQuery;

// Expose jQuery as an AMD module, but only for AMD loaders that
// understand the issues with loading multiple versions of jQuery
// in a page that all might call define(). The loader will indicate
// they have special allowances for multiple jQuery versions by
// specifying define.amd.jQuery = true. Register as a named module,
// since jQuery can be concatenated with other files that may use define,
// but not use a proper concatenation script that understands anonymous
// AMD modules. A named AMD is safest and most robust way to register.
// Lowercase jquery is used because AMD module names are derived from
// file names, and jQuery is normally delivered in a lowercase file name.
// Do this after creating the global so that if an AMD module wants to call
// noConflict to hide this version of jQuery, it will work.
if ( typeof define === "function" && define.amd && define.amd.jQuery ) {
    define( "jquery", [], function () { return jQuery; } );
}
```

So there are four ways to get jquery:
- jam module: use the global variable

``` javascript
require("jquery");
$ // use the global variable
```
- jam module: set the required flag

``` javascript
require("__webpack_amd_define").amd.jQuery = true;
var $ = require("jquery");
```
- own module: modify the original jquery source to export jquery

``` javascript
// jquery source
module.exports = jQuery;
```
- own module: load jquery source and export it properly

``` javascript
require("./jquery-1.8.0");
// require("script!./jquery-1.8.0.min.js"); // this would be more performant, but do not minimize
module.exports = jQuery;
```

I like the last one most, but I wanted to demonstrate jam. :-|

**Comment by Phoscur** [comment]
I've seen that part in jQuery,
Can I set that flag somewhere else?

**Comment by sokra** [comment]
We could set it in the [`__webpack_amd_require`](https://github.com/webpack/webpack/blob/master/buildin/__webpack_amd_require.js#L15) module in webpack, but I do not exactly understand what it means.

You only have to set it once. The `define.amd` object is shared across all modules.

**Comment by Phoscur** [comment]
I'm thinking of separting webpack from my source code. Maybe it could be set at compile time?
(That's somewhat like the reason I don't like the loaders too much. It makes the code dependent on webpack.)

**Comment by sokra** [comment]
You can create a file `__webpack_amd_define.js` in a modules folder i.e. `web_modules`:

``` javascript
var d = require("webpack/buildin/__webpack_amd_define");
d.amd.jQuery = true;
module.exports = d;
```

Not tested, but should work.

**Comment by sokra** [comment]
To clearify it: the code fragment I've posted above is only in the jam version of jQuery. It's not in the original jQuery.

**Comment by miffels** [comment]
+1 for the fourth option, writing an own module. I ran into the issue today when I was looking for a way to unify my node.js and client-side sources. For me, the solution looks as follows:

``` javascript
// jquery.js
'use strict';
var $ = require('jquery');

/*global jQuery */
if(typeof jQuery !== 'undefined') {
    $ = jQuery;
}

module.exports = $;
```

which can then be imported in your actual code using

``` javascript
// Some other module
var $ = require('./jquery');
```

both in webpacked JavaScript and node.js, assuming both files are in the same folder. My preferred solution would be having the aforementioned flag configurable somewhere else, e.g. in grunt.js or package.json, since I put generated and downloaded sources on the .gitignore list in order to keep my repository clean.

**Comment by sokra** [comment]
I changed a bit and you can now set the `require.amd` object at `webpackOptions.amd`.

i.e.

``` javascript
{
  amd: {
    jQuery: true
  }
}
```
