### ISSUE TITLE
window.webpackJsonp does not exist when running with --hot

### ISSUE THREAD

**Issue by zeen** [webpack/example-app#5]
`Uncaught TypeError: Cannot read property 'apply' of undefined`
on this line:
`oldWebpackJsonp.apply(null, arguments);` in `app.js`

Even with that line commented out (I'm assuming it's only important for updates, and not for initial load?), the area under _Choosen Sources_ remains empty.

I'm running it like this: `webpack-dev-server -d --colors --hot`

**Comment by sokra** [comment]
Try to run it with `node node_modules/webpack-dev-server/bin/webpack-dev-server -d --colors --hot`.

**Comment by zeen** [comment]
Same as before, `window.webpackJsonp` is undefined when it gets to that block of code. My example-app and all local and global npm packages are fully updated, no files have been modified. I'm on a OS X Mavericks.

My goal is to get --hot working for CSS live updates, and then for the whole React.js UI in some of my apps. Many of my apps have entirely stateless UIs, so --hot would be very interesting to use.
